language: java
jdk:
- openjdk7
cache:
  directories:
    - ~/.m2/repository
script: 
- mvn clean package
after_success:
- openssl aes-256-cbc -K $encrypted_98b2435d0832_key -iv $encrypted_98b2435d0832_iv -in key.asc.enc -out key.asc -d -d && gpg --fast-import key.asc
- mvn clean deploy -DskipTests --settings settings.xml -Pdeploy